### PR TITLE
FIXES NEED MERGE

### PR DESCRIPTION
**Pull request by Skyrimus**
1. [FIX] Fixed original Options menu
2. Moved application preferences in Options - ANDROID PORT SETTINGS
3. [FIX] Fixed saving changes in Options menu
4. Now can change graphics settings and more
5. Unlocked PLAYERS AND CONTROLS menu, can change crosshair and some features
6. Deleted SE1_00_Options.gro
7. Embedded configs in apk, automatic cfg files copying in to SeriousSam/Scripts folder

### CODE REVIEW

**Comment by aarcangeli** [comment]
Can you merge the master branch into your fork?

**Comment by Skyrimus** [comment]
Ok

**Comment by Skyrimus** [comment]
Maybe you give me contribution access to repository?

**Comment by Skyrimus** [comment]
Merged

**Comment by aarcangeli** [comment]
I don't really like the fact that the user has to put a new gro file.
Isn't there another way?

**Comment by Skyrimus** [comment]
User can use Script folder from steam game

**Comment by Skyrimus** [comment]
Just in new gro used advanced Rendering options cfg

**Comment by Skyrimus** [comment]
Screenshot_20190825-174003

**Comment by Skyrimus** [comment]
Screenshot_20190825-181338

**Comment by Skyrimus** [comment]
I think can use tool to unzip this configs from apk to SeriousSam folder without using gro file and download it

**Comment by Skyrimus** [comment]
Default rendering options is so useless, i included advanced Rendering options as default

**Comment by aarcangeli** [comment]
ok, so we can create something like "RenderingOptionsAndroid.cfg" and embed it in the apk

**Comment by Skyrimus** [comment]
Yeah

**Comment by Skyrimus** [comment]
You can do it? Cause i m not in my city now, i can send you new files

**Comment by Skyrimus** [comment]
To apply settings needed all Menu folder with ApplyShadowmaps.ini, ApplyTextures.ini, ApplyVideo.ini, GameOptions.cfg, Rendering options.cfg and SPOptions.cfg

**Comment by Skyrimus** [comment]
Like this 
Screenshot_20190825-191708

**Comment by Skyrimus** [comment]
Embedded!

**Comment by Skyrimus** [comment]
Fuck, some troubles on arm device, on x86 all works, finding solution

**Comment by Skyrimus** [comment]
Fixed, please merge

**Comment by Skyrimus** [comment]
All works stable :)

**Pull request merged**
